name: Lint & Format

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install linters & formatters
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Black (check only)
        run: black --check .

      - name: Flake8
        run: flake8 .

